default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: cchaves_development
  min_messages: warning
  username: pguser
  password: password

test:
  <<: *default
  database: cchaves_test
  min_messages: warning
  username: pguser
  password: password

#production: &production
#  <<: *default
#
